/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen.t2;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author User001
 */
public class FrameAula extends javax.swing.JFrame {

    private FrameSeleccionaClase  padre;
    DefaultListModel model = new DefaultListModel();
     List<Alumno> alumno = new ArrayList<>();
    public FrameAula(FrameSeleccionaClase padre) 
    {
        initComponents();
        this.padre =padre;
    }

    private FrameAula() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstAlumnos = new javax.swing.JList<>();
        bttTomarAsistencia = new javax.swing.JButton();
        bttAgregarAlumno = new javax.swing.JButton();
        lblCurso = new javax.swing.JLabel();
        lblTurno = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lstAlumnos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstAlumnos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 300, -1));

        bttTomarAsistencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examen/t2/Img/Group 1.png"))); // NOI18N
        jPanel1.add(bttTomarAsistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        bttAgregarAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examen/t2/Img/Group 2.png"))); // NOI18N
        bttAgregarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAgregarAlumnoActionPerformed(evt);
            }
        });
        jPanel1.add(bttAgregarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        lblCurso.setText("[Curso]");
        jPanel1.add(lblCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        lblTurno.setText("Turno");
        jPanel1.add(lblTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jLabel2.setText("Aula ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examen/t2/Img/image 1.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttAgregarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAgregarAlumnoActionPerformed
        FrameAgregarAlumno frameAgregarAlumno = new FrameAgregarAlumno(this);
        frameAgregarAlumno.setVisible(true);
    }//GEN-LAST:event_bttAgregarAlumnoActionPerformed

    public void AgregarAlumno(String nuevoNombre, String nuevoCodigo) {
    Alumno a = new Alumno(nuevoNombre, nuevoCodigo);
    alumno.add(a); // Agregar el nuevo alumno a la lista 'alumno'
    model.addElement(nuevoNombre); // Agregar el nombre del alumno al modelo de la lista
    lstAlumnos.setModel(model); // Actualizar la lista en la interfaz gráfica
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameAula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton bttAgregarAlumno;
    private javax.swing.JButton bttTomarAsistencia;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblTurno;
    private javax.swing.JList<String> lstAlumnos;
    // End of variables declaration//GEN-END:variables
}
